### PR TITLE
fix import of Part WB

### PR DESCRIPTION
**Pull request by tomate44**
Hello,
Your workbench look very interesting.
However, I had several errors at first try, all similar to :
"AttributeError: module 'FreeCAD.Part' has no attribute 'makeCircle'"
the culprit is "from FreeCAD import Part"
PS : I am running FC master, on Manjaro Linux

### CODE REVIEW

**Comment by mnesarco** [comment]
Hi @tomate44 , I cannot reproduce your Issue. I am using FC0.19 and FC0.18.4 on Linux Mint.

**Comment by mnesarco** [comment]
Confirmed, it is not compatible with FC0.18, but your PR is conflicting other files and I have found other parts that are non compatible with FC0.18.

**Comment by mnesarco** [comment]
I have fixed imports in all files to make it FC0.18 friendly, but it is not the only problem with FC0.18.

**Comment by tomate44** [comment]
OK. I just pulled your latest commits, and realized you fixed the imports.
It is working here, now.
Thanks a lot. I am closing the PR.

**Comment by mnesarco** [comment]
Unfortunately, custom shapes does not work with FC0.18 at the moment.

**Comment by mnesarco** [comment]
BTW, the Wiki contains some useful info now: https://github.com/mnesarco/MarzWorkbench/wiki

**Comment by tomate44** [comment]
I am using FC 0.19,so I was able to give a test at importing a body shape.
Great work!
